import AVFoundation
import CoreML
import CoreLocation

// Real-time inference using a CoreML classifier + Swift mel spectrogram.
// Falls back to the mock identifier when no model is present.
//
// Pipeline:
//   raw audio (48 kHz mono) → MelSpectrogramExtractor → CoreML classifier → label
//
// The CoreML model is generated by extract_birdnet.py from the BirdNET TFLite file.
// Model inputs:  mel_spec_1 [1, 96, 511, 1] + mel_spec_2 [1, 96, 511, 1]
// Model output:  classifierOutput [1, N]  — sigmoid probability per species
final class BirdNETAnalyzer: NSObject {

    var onDetection: ((String, String, Double) -> Void)?
    var locationProvider: (() -> CLLocationCoordinate2D?)?
    private(set) var usingRealModel = false

    private var classifier: MLModel?
    private var labels: [String] = []
    private var locationFilter: LocationFilter?
    private let melExtractor = MelSpectrogramExtractor()

    // Shared accumulator — both real and mock paths use 3-second windows
    private var accumulator: [Float] = []
    private let windowSize = 144_000   // 3 s × 48 000 Hz
    private let mockIdentifier = BirdIdentifier()

    // MARK: - Setup

    func setup(modelPath: String?, labelsPath: String?, weightsPath: String? = nil) {
        classifier = nil
        usingRealModel = false
        accumulator = []
        labels = []
        locationFilter = nil

        if let path = labelsPath,
           let content = try? String(contentsOfFile: path, encoding: .utf8) {
            labels = content.split(separator: "\n").map(String.init).filter { !$0.isEmpty }
        }

        if let path = weightsPath {
            locationFilter = LocationFilter(weightsPath: path)
        }

        guard let path = modelPath else { return }

        do {
            let url = URL(fileURLWithPath: path)
            let config = MLModelConfiguration()
            config.computeUnits = .all
            classifier = try MLModel(contentsOf: url, configuration: config)
            usingRealModel = true
        } catch {
            print("[BirdNETAnalyzer] CoreML load failed: \(error)")
        }
    }

    // MARK: - Analysis

    func analyze(buffer: AVAudioPCMBuffer) {
        guard let data = buffer.floatChannelData?[0] else { return }
        let samples = Array(UnsafeBufferPointer(start: data, count: Int(buffer.frameLength)))
        accumulator.append(contentsOf: samples)

        while accumulator.count >= windowSize {
            let window = Array(accumulator.prefix(windowSize))
            accumulator = Array(accumulator.dropFirst(windowSize / 2)) // 50 % overlap

            if usingRealModel {
                runInference(on: window)
            } else {
                mockIdentifier.identify(samples: window) { [weak self] detection in
                    guard let d = detection else { return }
                    self?.onDetection?(d.commonName, d.scientificName, d.confidence)
                }
            }
        }
    }

    // MARK: - CoreML Inference

    private func runInference(on samples: [Float]) {
        guard let model = classifier else { return }

        guard let (spec1, spec2) = melExtractor.extract(from: samples) else {
            print("[BirdNETAnalyzer] Mel spectrogram extraction failed")
            return
        }

        do {
            let input = try MLDictionaryFeatureProvider(dictionary: [
                "mel_spec_1": MLFeatureValue(multiArray: spec1),
                "mel_spec_2": MLFeatureValue(multiArray: spec2)
            ])
            let output = try model.prediction(from: input)
            if let probs = output.featureValue(for: "classifierOutput")?.multiArrayValue {
                parseTopResult(from: probs)
            }
        } catch {
            print("[BirdNETAnalyzer] Inference error: \(error)")
        }
    }

    private func parseTopResult(from probs: MLMultiArray) {
        let threshold = Float(UserDefaults.standard.double(forKey: "confidence_threshold").isZero
                             ? 0.7
                             : UserDefaults.standard.double(forKey: "confidence_threshold"))

        // Compute location mask if the feature is enabled and location is available
        var mask: [Bool]? = nil
        if UserDefaults.standard.bool(forKey: "use_location_filter"),
           let filter = locationFilter,
           let coord = locationProvider?() {
            mask = filter.allowedMask(lat: coord.latitude, lon: coord.longitude, date: Date())
        }

        // Find the highest logit among allowed species
        let count = probs.count
        var topIndex = 0
        var topLogit: Float = -.infinity
        for i in 0..<count {
            if let mask, !mask[i] { continue }
            let v = probs[i].floatValue
            if v > topLogit { topLogit = v; topIndex = i }
        }

        // Apply sigmoid to convert logit → probability
        let probability = 1.0 / (1.0 + exp(-topLogit))
        guard probability >= threshold else { return }

        let confidence = Double(probability)
        let label = topIndex < labels.count ? labels[topIndex] : "Unknown_Unknown"

        // BirdNET label format: "Turdus migratorius_American Robin"
        let parts = label.split(separator: "_", maxSplits: 1).map(String.init)
        let scientific = parts.first ?? label
        let common     = parts.count > 1 ? parts[1] : label

        onDetection?(common, scientific, confidence)
    }
}
